import { Device } from "./app/shared/models/Device";

export const sample_devices: Device[] = [
  {
    "id": "1",
    "name": 'Apple IPhone 14',
    "price": 990,
    "tags": ['Apple','iPhone'],
    "favorites": true,
    "stars": 5,
    "imageUrl": 'assets/iPhone-14.jpg',
    "origin": ["Thaiwan","Califonia"],
    "description": ["A15 Bionic chip", "Vibrant Super Retina XDR display", "Aerospace - grade aluminum"],
  },
  {
    "id": "2",
    "name": 'Apple IPhone 13',
    "price": 800,
    "tags": ['Apple','iPhone'],
    "favorites": false,
    "stars": 4,
    "imageUrl": 'assets/iPhone-13.jpg',
    "origin": ["Thaiwan","Califonia"],
    "description": ["A15 Bionic chip", "Cinematic mode", "Super Retina XDR Display"],
  },
  {
    "id": "3",
    "name": 'Galaxy A73 5G',
    "price": 500,
    "tags": ['Samsung','Galaxy','5G'],
    "favorites": false,
    "stars": 4,
    "imageUrl": 'assets/A73.jpg',
    "origin": ["China","Vietnam"],
    "description": ["Snapdragon® 778G 5G", "Hyperfast 5G connection", "120Hz Super AMOLED Plus display"],
  },
  {
    "id": "4",
    "name": 'Galaxy Z Fold4',
    "price": 900,
    "tags": ['Samsung','Galaxy','Z','Fold'],
    "favorites": true,
    "stars": 5,
    "imageUrl": 'assets/fold4.jpg',
    "origin": ["China","Vietnam"],
    "description": ["Unfold your phone’s potential", "The only IPX8 water-resistant foldable series", "New Taskbar for PC-like multitasking"],
  },
  {
    "id": "5",
    "name": 'Google Pixel 7 Pro',
    "price": 500,
    "tags": ['Google','Pixel'],
    "favorites": false,
    "stars": 3,
    "imageUrl": 'assets/pixel7.jpg',
    "origin": ["China"],
    "description": ["10-120Hz Smooth Display with LTPO9", "IP68 water resistance", "The pro-level triple rear camera system"],
  },
  {
    "id": "6",
    "name": 'Redmi Note 11 Pro 5G',
    "price": 150,
    "tags": ['Redmi','Note','5G'],
    "favorites": false,
    "stars": 3,
    "imageUrl": 'assets/redminote11.jpg',
    "origin": ["China"],
    "description": ["FHD+ AMOLED display", "108MP Pro-grade main camera", "Liquid Cool technology"],
  },
  {
    "id": "7",
    "name": 'JBL GO 2 Portable Speaker',
    "price": 50,
    "tags": ['JBL','Speaker','Bluetooth'],
    "favorites": true,
    "stars": 4.5,
    "imageUrl": 'assets/jblgo2.jpg',
    "origin": ["China","Singapore"],
    "description": ["Wireless Bluetooth Streaming", "Up to 5 hours of Playtime"],
  },
  {
    "id": "8",
    "name": 'JBL LIVE 650BTNC Headphone',
    "price": 70,
    "tags": ['JBL','Headphones','Noice cancelling'],
    "favorites": true,
    "stars": 3.8,
    "imageUrl": 'assets/jblliveh.jpg',
    "origin": ["China","Singapore"],
    "description": ["Up to 30 hours battery life with ANC off and Speed Charge", "Press play. Mute distractions", "Get help from your Voice Assistant","JBL Signature Sound"],
  },
]
